### ISSUE TITLE
Cannot Find Function eigenDecompose

### ISSUE THREAD

**Issue by chickweed01** [mattt/Surge#117]
I loaded the Surge project into XCode. I cannot locate the "eigenDecompose" function. Has it been removed or renamed? The unit tests are there.

Thank you

**Comment by regexident** [comment]
Have you tried doing a text search in the checked out project for the function name used in the unit tests? Xcode is notoriously unstable when it comes to its `command`-click function.

Otherwise the current `master` has the functions located here:

https://github.com/mattt/Surge/blob/898a908c35e4a56a645b1648e1f10fe64510f055/Sources/Surge/Linear%20Algebra/Matrix.swift#L684-L748

Keep in mind that `master` received a bunch of major (albeit hopefully non-breaking) changes (e.g. splitting up files, moving stuff around, etc.) three weeks ago that have not yet been released/tagged. So you might want to check out the latest tag’s state of things (or your local checkout) instead.

**Comment by chickweed01** [comment]
Thank you for your reply. The issue is on me - i downloaded an older version by mistake :(
