### ISSUE TITLE
How to install the framework for usage in Playgrounds and Xcode?

### ISSUE THREAD

**Issue by shyamalschandra** [mattt/Surge#36]
I built the Surge.framework but I cannot show the framework in the Finder.  What to do?

How do I build the framework so that I can just put it into the Xcode project?

Thanks!

**Comment by rprechelt** [comment]
If you have not already solved this, please see [this link](https://developer.apple.com/library/ios/recipes/Playground_Help/Chapters/ImportFramework.html). Surge does not currently build to a binary framework file; the `Surge.xcodeproj' and the associated files **are** the framework in a sense.

**For use in a Playground**
I've laid out a rough guide below but please peruse the link above for more details:

1. To use Surge in a Playground, create a new XCode Workspace (File > New > Workspace).
2. Create a Playground (File > New > Playground)
3. Add the Playground to the Workspace (File > Add Files to "Workspace Name Here" then select your playground)
4. Add the Surge.xcodeproj to the Workspace (File > Add Files to "Workspace Name Here" then select the Surge.xcodeproj which should be in the same directory as the Workspace).
5. You can then `import Surge` in your Playground, and it should work as expected. 

There is also the demo playground that is included with the Surge repository that I would recommend looking at for some of the basic uses of Arithmetic, Matrices and the FFT. 

**For use in an XCode Project**
A similar process can be used; again, please see the Apple documentation for more details. Again, this is only one method of adding Surge to your project, not the only one. This is the method that works on the several machines that I have added Surge to, but others/you may use a different process. 

1. Add the Surge.xcodeproj to your project (File > Add Files to "Project Name Here" and then select Surge.xcodeproj which should be in the same directory as your project)
2. Go to Project Settings > General > Linked Frameworks and Libraries > '+' and then select Surge.framework from the list
3. Go to Build Phases and Surge.Framework to Target Dependencies and Link Binary With Libraries
4. Drag the entire Link Binary with Libraries section so that it is immediately after Target Dependencies
5. You should then be able to `import Surge` from any file in your project.

Let me know if you have any difficulties.

**Comment by imanmk** [comment]
Hello,

I get this error when I'm building my project with Surge:

"Binary operator '-' cannot be applied to two '[Double]' operands" in Arithmetic.swift - Distance section

**Comment by rprechelt** [comment]
Hello,

This is because the latest commit to Surge was incomplete (the `-` operator was not implemented) and therefore will not build. I have submitted a pull request for this issue but I do not know when it will be merged into master. If you wish to continue using Surge, I would checkout commit 2c89872b543a4d916e90e75de655f900b15914b5 or think about using one of the many good Surge alternatives as Surge appears to no longer be developed regularly.

**Comment by imanmk** [comment]
I see. What Surge alternative would you recommend? Also, do you know of any good alternatives to iOS-Charts framework? That seems to have some issues too.

Thanks in advance!

**Comment by rprechelt** [comment]
The most well-developed alternative to Surge that I am aware of is [Upsurge](https://github.com/aleph7/Upsurge) which is a fork of Surge; it has more features than Surge and is developed more regularly. It has added support for matrices and tensors that make working with multi-dimensional data easier. I am also building a Surge alternative called Wave which is more focused on digital signal processing (rather than matrix mathematics) but it is not production-ready and is still being heavily developed by me so I would not recommend using it for production code (YET).

**Comment by imanmk** [comment]
Cool! Thank you.

**Comment by imanmk** [comment]
By any chance, do you know of any reliable library for plotting data (e.g. scatter chart) in Swift?

**Comment by rprechelt** [comment]
No I don't unfortunately; plotting charts is not within my Swift realm of expertise. Enjoy whatever DSP framework you end up choosing!

**Comment by rfdickerson** [comment]
@rprechelt Thank you for your PR request for Surge that fixed the build problem. We should look into getting Travis instrumented on Surge shortly.

**Comment by aleph7** [comment]
@imanmk have a look at https://github.com/aleph7/plotkit

**Comment by cmerger** [comment]
May I ask you a question? I am new to swift and playground. I saw your post about surge. I am trying to import 2 dependencies in a Playground (Alamofire and SSZipArchive) with no success. I have tried to do it as you describe it, but these dependencies do not show up when I import them. Is your method only working with surge or should it work with any dependencies? Thanks
ps: your link in the first sentence goes to a blank page.
