### ISSUE TITLE
xcode 9.4.1 -carthage update - 2.1.0 -  error: Shorthand Operator Violation: Prefer shorthand operators (+=, -=, *=, /=) over doing the operation and assigning. (shorthand_operator)

### ISSUE THREAD

**Issue by johndpope** [mattt/Surge#82]
```shell
/Users/jpope/Documents/gitWorkspace/Akari3/Carthage/Checkouts/Surge/Sources/Surge/Matrix.swift:432:13: error: Shorthand Operator Violation: Prefer shorthand operators (+=, -=, *=, /=) over doing the operation and assigning. (shorthand_operator)
/Users/jpope/Documents/gitWorkspace/Akari3/Carthage/Checkouts/Surge/Sources/Surge/Matrix.swift:460:13: error: Shorthand Operator Violation: Prefer shorthand operators (+=, -=, *=, /=) over doing the operation and assigning. (shorthand_operator)
```
using this repo -
carthage update --platform osx
https://github.com/daisukeokaoss/Akari3

**Comment by johndpope** [comment]
<img width="1965" alt="screen shot 2018-08-13 at 11 46 08 am" src="https://user-images.githubusercontent.com/289994/44042538-83c3e128-9eee-11e8-92e9-2c9e98ec1188.png">

**Comment by johndpope** [comment]
seems to bypass error. 
```swift
public func det(_ x: Matrix<Double>) -> Double? {
    var decomposed = x
    var pivots = [__CLPK_integer](repeating: 0, count: min(x.rows, x.columns))
    var info = __CLPK_integer()
    var m = __CLPK_integer(x.rows)
    var n = __CLPK_integer(x.columns)
    _ = withUnsafeMutableMemory(&pivots, &(decomposed.grid)) { ipiv, grid in
        withUnsafeMutablePointers(&m, &n, &info) { m, n, info in
            dgetrf_(m, n, grid.pointer, m, ipiv.pointer, info)
        }
    }

    if info != 0 {
        return nil
    }

    var det = 1 as Double
    for (i, p) in zip(pivots.indices, pivots) {
        if p != i + 1 {
            det = -det * decomposed[i, i]
        } else {
            let detNew =  det * decomposed[i, i]
            det = detNew
        }
    }
    return det
}
```

**Comment by johndpope** [comment]
github "johndpope/Surge" ~> 2.1.1

**Comment by mattt** [comment]
@johndpope You're reporting a diagnostic generated by SwiftLint. This isn't a compiler error, and doesn't inherently prevent users from building their project. 

This project defines a `.swiftlint.yml` file, but doesn't enforce the `shorthand_operator` rule. Looking at this particular case, I don't agree with the advice to prefer shorthand operators, and don't believe we should opt-in to this here.  

I believe the general recommendation is to exclude 3rd-party dependencies from `swiftlint` coverage, because such violations aren't directly actionable. You can do this by adding the following to your `.swiftlint.yml` file: 

```yaml
excluded:
- Carthage
- Pods
```

**Comment by johndpope** [comment]
Makes sense. I’m fine with this. But request that a note is added in source to point somewhere explaining this. Otherwise others will trip up and have to search around for solution. Or add to read me as known issue. Or let’s raise an issue with swift lint to rectify and link here.

**Comment by johndpope** [comment]
Whoops on mobile and see you’re one step ahead. Thx
